project:
  type: website
  resources:
    - assets/fonts/*

website:
  title: "fonts-test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      - cosmo
      - assets/fonts.scss
    css: styles.css
    toc: true
